### ISSUE TITLE
Inconsistent geometry restrictions

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#100]
[Building](https://www.cityjson.org/specs/1.1.0/#building) chapter:

> The geometry of "Building", "BuildingPart", "BuildingStorey", "BuildingRoom", and "BuildingUnit" can only be represented with these Geometry Objects: (1) "Solid", (2) "CompositeSolid", (3) "MultiSurface".
> The geometry of "BuildingInstallation", "BuildingConstructiveElement", or "BuildingFurniture" objects can be represented with any of the Geometry Objects.

[Bridge](https://www.cityjson.org/specs/1.1.0/#bridge) chapter:

>The geometry of both "Bridge" and "BridgePart" can only be represented with these Geometry Objects: (1) "Solid", (2) "CompositeSolid", (3) "MultiSurface". The geometry of the four other objects can be represented with any of the Geometry Objects.

Thus, "BridgeRoom" (and also "TunnelHollowSpace") can have any geometry type, but "BuildingRoom" is restricted to solids and surfaces. Why?

**Comment by hugoledoux** [comment]
Why? Because I actually couldn't really find this information from the specs/UML of CityGMLv3. Perhaps it's me though...

But let's follow the data model specs here: what should it be? `"Bridge"` and `"BridgePart"` also restricted to (1) "Solid", (2) "CompositeSolid", (3) "MultiSurface"?

**Comment by clausnagel** [comment]
Well, I was just stumbling across the "BuildingRoom" being restricted to (1) "Solid", (2) "CompositeSolid", (3) "MultiSurface", whereas "BridgeRoom" and "TunnelHollowSpace" are not. I think this should be consistent.

"Bridge" and "BridgePart" and are already restricted to (1) ..., (2) ... and (3) ... which is consistent with "Building", "BuildingPart", "Tunnel" and "TunnelPart". So, that's fine I guess.

**Comment by clausnagel** [comment]
Looking at the schemas again, I realized that the allowed geometries for `"_AbstractBuilding"` are actually different from `"Bridge"` and `"Tunnel"`.

`"_AbstractBuilding"` can only have `"MultiSurface"`, `"Solid"` and `"CompositeSolid"`, whereas tunnels and bridges (+ their parts) can additionally have `"MultiSolid"` and `"CompositeSurface"` in addition. The spec, however, does not mention the latter two for bridges and tunnels. So, I think this should be harmonized as well.

**Comment by hugoledoux** [comment]
so the solution to harmonise all this would be if the 4 objects Tunnel/Part and Bridge/Part are restricted to "MultiSurface", "Solid" and "CompositeSolid", right?
