### ISSUE TITLE
Restrict LoD1 to solid geometries?

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#101]
Based on several requests from the CityGML community, the possibility to use MultiSurfaces for the LoD1 representation of city objects such as buildings was removed from CityGML 3.0. LoD1 geometries are simple extrusions, so it should be easy for software to create a watertight Solid geometry.

As far as I understand, CityJSON 1.1 however still supports MultiSurfaces for LoD1 representations. Should a similar restriction be added to CityJSON?

**Comment by hugoledoux** [comment]
Hmmmm, it's not something that can be done with the schemas (or that would complicate a whole lot of things) so I'll leave it like this.
