### ISSUE TITLE
Geometries of CityObjectGroup

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#102]
[CityObjectGroup](https://www.cityjson.org/specs/1.1.0/#cityobjectgroup) chapter:

> may have a member "geometry", although only one geometry is allowed in the array of geometries. Notice that the "lod" property is rather meaningless, but is used to enforce uniformity with all the other geometries.

CityGML 2.0 also just allowed one geometry for CityObjectGroup,  which did not have an LoD identifier. With CityGML 3.0, a CityObjectGroup can be represented as any other city object in multiple LoDs. Should this restriction be dropped from CityJSON 1.1? Could make sense to provide a simplified LoD1 or even LoD0 geometry for the group that, for instance, embraces its members.

**Comment by hugoledoux** [comment]
oh I had not realised this, thanks for pointing this out. And yes that should be changed indeed, it makes sense too.

For v1.1.1 then, I'll bundle your comments and release a patch
