### ISSUE TITLE
Version pattern for extensions too restrictive

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#104]
The current pattern `"^(\\d\\.)(\\d)$"` for the version of extensions in `cityjson.schema.json` seems to be too restrictive as it only allows one digit for the major and minor version. Thus, something like `1.10` or `10.1` is not allowed. I suggest changing the pattern to `"^(\\d+\\.)(\\d+)$"`.

**Comment by hugoledoux** [comment]
haha, we were not planning to reach this maturity I think!
