### ISSUE TITLE
`vertex-texture` or `vertices-texture`?

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#105]
There is mixed information in the specs whether the Appearance object can have `vertex-texture` or `vertices-texture`. Which one is true?

For instane https://github.com/cityjson/specs/blame/main/specs/specs.bs#L1174 vs. https://github.com/cityjson/specs/blame/main/specs/specs.bs#L1182

**Comment by hugoledoux** [comment]
oh wow, thanks for catching this.

it's `"vertices-texture"`, only this in the schema.
