### ISSUE TITLE
Harmonize enum of trafficDirection with CityGML 3.0

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#107]
From the few predefined attributes of `"CityObjects"`, the attribute `"trafficDirection"` defined for `"_AbstractTransportationWay"` is also defined in CityGML 3.0 for `AbstractTransportationSpace`. Both are defined as `enum` but the allowed values do not match: In CityJSON 1.1, one may use `"one-way"` and `"two-way"` whereas the values are restricted to `forwards`, `backwards` and `both` in CityGML 3.0.

It would be great to harmonize the allowed values in order to make data conversions easier. Maybe by simply adding the CityGML values to the enum in CityJSON?

**Comment by hugoledoux** [comment]
I had forgotten about that property, I guess in the spirit of CityJSON v1.1 I should just remove it, no?

You wrote "From the few predefined attributes of "CityObjects"", but if I am not mistaken this is the only one (except the "location" for the position of the entrance door). Am I missing something?

So either (1) remove the enum, or (2) add the v3 ones to the list. I would vote for (1) personally, you?

**Comment by clausnagel** [comment]
I was also counting `"children_roles"` for CityObjectGroup although it's different because it's outside `"attributes"`.

I agree that removing `"trafficDirection"` is in the spirit of CityJSON v1.1. So, I second your proposal.
