### ISSUE TITLE
Explain each CityObject type

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#117]
Currently the various CityObject types are simply listed in the specs. While it is fairly straightforward what real world object should be modelled as `Building` or `Tunnel`, it can be somewhat ambiguous in case of the 2nd-level CO-s.

The [CityGML conceptual model](https://docs.ogc.org/is/20-010/20-010.html) contains a one-liner Class definition for each of these objects, eg. Table 66.

Right now the CityJSON specs assume that the reader is familiar with these CityGML class definitions or at least knows how to look them up. However, I think it would be better if the CityJSON specs are self-contained, or at least contain the links to the relevant section in the CityGML conceptual model.

Personally, I wouldn't use the term *definition* for these CityObject explanations, because it is too restrictive and undoubtedly some things will be missed. The description of [OtherConstruction](https://www.cityjson.org/specs/1.1.1/#otherconstruction) is fine I think, and it would be good to see similar explanations for the rest of the CO types.

**Comment by hugoledoux** [comment]
ce2be2b8d460f13574faf0d85d2ab8a6f27d3ae2
