### ISSUE TITLE
Change transform dummy exemple

### ISSUE THREAD

**Issue by GANys** [cityjson/specs#119]
Specifications should be updated from

```
"transform": {
    "scale": [0.0, 0.0, 0.0],
    "translate": [1.0, 1.0, 1.0]
  }
```
into

```
"transform": {
    "scale": [1.0, 1.0, 1.0],
    "translate": [0.0, 0.0, 0.0]
  }
```

at https://www.cityjson.org/specs/1.1.1/#cityjson-object (the rest of specs is good).

Otherwise, it is not a working exemple. Actually, until you don't transform or vizualize models, it is.

**Comment by hugoledoux** [comment]
ah right, well we just put dummy numbers there but I see your point.
