### ISSUE TITLE
CityJSONFeatures: all children or only one-level below?

### ISSUE THREAD

**Issue by hugoledoux** [cityjson/specs#136]
right now it's only "one level below the current one", but that makes no sense, does it?

If a `"Building"` has 3 `"BuildingPart"` and those have `"BuildingInstallation"` and then how are we supposed to link the installations to the BPart?

I'd say *all* the children

**Comment by balazsdukai** [comment]
True, I missed this before.
I would change the requirement then to:

- must have one member with the name "CityObjects". The value of this member is a collection of key-value pairs, where the key is the ID of the object, and the value is one City Object. The ID of a City Object should be unique (within one CityJSONFeature Object), and all the children of the "CityJSONFeature" must be listed.

**Comment by hugoledoux** [comment]
made it clearer that all under are included, and added this to the snippet

- **must** have one member with the name `"CityObjects"`. The value of this member is a collection of key-value pairs, where the key is the ID of the object, and the value is one City Object. The ID of a City Object should be unique (within one `"CityJSONFeature"`), and all the children of the `"CityJSONFeature"` must be included (and the children of the children (recursively), if there are any).
