### ISSUE TITLE
What are "complex geometries" in an Extension?

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#140]
The specs say that one can define "complex geometries" in an extension. However, there is not further description or example on this, neither do the schemas reflect this.

So what is a complex geometry actually? Is it any geometry that is not among the [7 types of the core specs](https://www.cityjson.org/specs/1.1.2/#arrays-to-represent-boundaries)?

E.g. a `LineString` ?

```json
{
  "type": "LineString",
  "lod": "1",
  "boundaries": [2, 3, 5]
}
```

If this is so, and one can define new geometries, then this pretty much breaks one of the main advertisement points of CityJSON Extensions, that implementing software can "just" use extended files. It's even written in the specs, *"CityJSON Extensions are designed such that they can be read and processed by standard CityJSON software, often no changes in the parsing code is required."*

**Comment by hugoledoux** [comment]
I have no idea how we could leave that "complex geometries" there. NO it's not new-and-fancy geometries, since we want to *avoid* this mess (which ADEs have).

So it should be: "and defining its possible geometries".
