### ISSUE TITLE
Clarify different geometries for extended CityObject

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#142]
The specs in [8.6](https://www.cityjson.org/specs/1.1.2/#rules-to-follow-to-define-new-city-objects) say that "If a new City Object contains other objects and requires different geometries [...]". What is meant by "different geometries" here? Is this related to the complex geometries #140 ?

**Comment by hugoledoux** [comment]
I wrote this, I should know what is meant, but it's not clear :\

I meant this I assume, which should be clear:

Existing City Objects cannot be extended and have new types as children, eg it is not allowed to add a new City Object ”Balcony” to a ”Building”.  Instead, a new type, eg ”FancyBuilding” should be created, which can have a `"Balcony"` as a potential children.
