### ISSUE TITLE
Required properties in Semantic Objects with Extension?

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#144]
It is possible to create new City Object types and require City Object attributes with an extension.
It is possible to create new Semantic Object types. So one would expect that the Semantic Object attributes can be extended the same way as for City Objects. However, this is not clear in the specs.

Also, how would one create an extended Semantic Object schema? For City Objects we have the "extraAttributes", but there is no equivalent for Semantic Objects.

**Comment by hugoledoux** [comment]
> Also, how would one create an extended Semantic Object schema?

Not possible at this moment, is this something we really want? It's more custom code for validation, but could be done in v1.2 actually with a fourth category. The custom would just parse the file for semantic surfaces starting with the "+" sign, and verify that it's in the list of "approved" semantic surfaces.
