### ISSUE TITLE
Building "address" is a JSON object but Metadata "address" is string.

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#149]
"A City Object of type "Building", "BuildingPart" or "BuildingUnit" may have a member "address", consisting of an array of JSON objects listing one or more addresses of that building (an apartment building could contain several for instance). The properties of an address JSON object are free format, to accommodate the different ways addresses are described in different countries."

But the `metadata.pointOfContact` may have one member with the name "address". The value is a string with the full address.

Shouldn't we harmonize?

**Comment by hugoledoux** [comment]
But aren't they already harmonised since both free format? I am not sure I follow you here.

**Comment by hugoledoux** [comment]
Only the snippet I left the old xAL properties, I guess you meant that? Should we use the same properties as in the metadata you mean?

**Comment by balazsdukai** [comment]
I meant that the Bulding* address has a value of JSON *object*, while the metadata address is a JSON *string*.
I think both should have the same value type, either string or object.

**Comment by hugoledoux** [comment]
oh right I see now, stupid me...

We I think that would be too much of a break for a patch, no? But yes it should be harmonised, good point.

**Comment by balazsdukai** [comment]
Yes, that's true. Let's keep this open for the next minor (or major) release.
Related to https://github.com/cityjson/specs/discussions/137

**Comment by balazsdukai** [comment]
Agreed.
