### ISSUE TITLE
Normals orientation 

### ISSUE THREAD

**Issue by I-Sokolov** [cityjson/specs#157]
Has cityJSON any agreements and/or requirements for normals orientation and consistency for rings (loops) of surfaces?
Can we trust CCW for outer rings and CW for holes?
Must surfaces be drawn two- or one-sided?
Maybe these things are inherited from cityGML?
I'd like to see some hints in the documentaion.

**Comment by hugoledoux** [comment]
Good point, the specs should mention this indeed.

Basically: it's inherited from CityGML and ISO19107 is used for the primitives.

The relevant rules are explained there: https://val3dity.readthedocs.io/en/latest/definitions/

> Can we trust CCW for outer rings and CW for holes?

Yes, if you look at the surface from the outside 

> Must surfaces be drawn two- or one-sided?

one-sided
