### ISSUE TITLE
Add "+GenericSurface" to the Generic extension

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#183]
CityGML 3.0 offers the `GenericThematicSurface` feature type that can be used to model boundary surfaces which are not covered explicitly by a predefined class such as WallSurface or GroundSurface (see [here](https://docs.ogc.org/is/20-010/20-010.html#GenericThematicSurface-section)). 

Since CityJSON 2.0 introduces the possibility to define "extraSemanticSurfaces" in an extension, it would be nice to add this feature type to the "Generic" extension available from [cityjson.org](https://www.cityjson.org/extensions/download/v20/generic.ext.json). Possible type names could be "+GenericThematicSurface" (more CityGML-like), "+GenericSemanticSurface" (more CityJSON-like), or simply "+GenericSurface".

**Comment by hugoledoux** [comment]
Good idea! 

Done: https://github.com/cityjson/website/commit/0241531cb83ee4da48d29168ed1d4df1ad5e181b
