### ISSUE TITLE
I'm working on converting IFC to CITYJSON.

### ISSUE THREAD

**Issue by Pdongjaelee** [cityjson/specs#198]
hello.
I'm working on converting IFC to CITYJSON.

Currently, IFCOPENSHELL is used to extract geometry information from IFC data.

Now I just need to create this data as a CITYJSON file, but I keep getting an error.

I mainly used cjio to create cityjson, but is there another way?

**Comment by Pdongjaelee** [comment]
hello.
I am using cjio to convert ifc to cityjson.

Could you please take a look at my code?

**Comment by hugoledoux** [comment]
cjio cannot convert IFC to CityJSON I'm afraid, it only reads CityJSON and OBJ as input.

**Comment by Pdongjaelee** [comment]
Ah, I have a lot of obj files.

If I have an obj file, can I convert it to cityjson using cjio?
