### ISSUE TITLE
Convert ifc to cityjson?

### ISSUE THREAD

**Issue by Pdongjaelee** [cityjson/specs#199]
hello
I am researching to convert ifc to cityjson.

I'm currently having a hard time with not much data.

Is there a way to convert ifc to cityjson?

**Comment by hugoledoux** [comment]
this has already been answered:
https://github.com/cityjson/cjio/discussions/186
https://github.com/jaspervdv/IFC_BuildingEnvExtractor/issues/3

please do not open issues for this, it's not related at all to the specs of CityJSON
