### ISSUE TITLE
Parent Property Energy Extension

### ISSUE THREAD

**Issue by phiberg** [cityjson/specs#45]
The switch over from the `"parent"` to the `"parents"` attribute as well as the introduction of the new `"toplevel"`attribute (as discussed in Issue [#38](https://github.com/tudelft3d/cityjson/issues/38)) seem not to be incorporated in the schema files of the Energy Extension. 

When I try to validate a file in cjio according to the Energy schema file e.g. `"parent": "string"`
 I get: KeyError: 'parents'

When I try to do it according to the docs v0.9 e.g. `"parents": [array]` I get the error: Additional properties are not allowed ('toplevel', 'parents' were unexpected)

Also, is the `"toplevel": Boolean` to be used within the `"attributes"` or the `"geometry"` property, because in the docs/extensions in paragraph "2. Creating/extending new City Objects" the attribute is written in the `"attributes"` property and in the last paragraph "Adding complex types for CityFurniture" the attribute is written in the `"geometry"` property. 

Side-question regarding the Energy extention:
Is the energy-physics.json schema file still needed? As far as I get it from what is written here, the mechanism for extending the `AbstractBuilding` type with the `energy-attributes` has been revamped so that `+AttributeName` within the normal building type is now to be used and not the `+EnergyBuilding` type anymore.

Otherwise thank you for all the great work so far, I find this encoding a lot more comprehensive and easier to handle than its gml counterpart.

**Comment by hugoledoux** [comment]
Indeed, the Energy Extension hasn't been updated for v09. The main reason is that I didn't know that anyone was interested! But if you are then perhaps you want to help us to update--and maintain--it? I'm happy to receive pull requests, and also to help in adding the missing features.

**Comment by phiberg** [comment]
Surprise surprise you have an interested person :) 

I'm using it for my master thesis and you may also know my supervisor from the citygml workshop in delft. I already implemented the `parents` and `toplevel` stuff into the schema because I needed it for my initial progress. Also it may be the case, that I need to complete the missing distribution and conversion system modules for the energy schema, but this will heavily depend on my time management. I'm fairly new to this and have no experience in handling all the mechanics of the git system but I will contribute what I can in the course of my project.

**Comment by hugoledoux** [comment]
@phberg don't know the status of your work, but here at tudelft we're working on this now, see https://github.com/ozgetufan/cjenergy/
