### ISSUE TITLE
"lod" should be string

### ISSUE THREAD

**Issue by kenohori** [cityjson/specs#52]
Since `"lod"` supports the [improved LoDs](https://3d.bk.tudelft.nl/lod/), it is not a good idea to store it as a number because of floating-point intricacies. Once parsed, the actual number stored in memory will not be the same, and so simple tests like `"lod" = 3.3` might fail. Much safer to store as a string.

LoD 1.1 stored as a float: 1.10000002384185791015625
LoD 3.3 stored as a float: 3.2999999523162841796875

**Comment by balazsdukai** [comment]
`lod` is not a string?! :-)  I'm casting it to a string for exactly this reason...

**Comment by hugoledoux** [comment]
totally agree with you both, it should be a string. Version is a string, and it's the same.

for 1.0.1 thus
