### ISSUE TITLE
Add an example for an empty, and minimal-valid CityObject

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#59]
Just as in case of the whole CityJSON object, add examples for  *minimal valid* CityObjects and *empty* CityObjects. Ideally for each CityObject type.

**Comment by hugoledoux** [comment]
this was done for Buildings only, I felt that for all was getting too verbose/messy for the specs. Maybe as separate files? 

7c33e2fa26d95c7f7e4ddbcdcc0f51c1001a8294
