### ISSUE TITLE
Chunk-wise parsing/writing of CityObjects

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#6]
The current layout of a CityJSON dataset requires access to the `"vertices"` array in order to be able to process a city object. This hinders implementing a streaming parser that would be able to read city objects as individual chunks. Benefits of a chunk-wise parsing approach would be, for instance, that you do not have to read the entire CityJSON dataset into main memory but that chunks can already be forwarded to other threads for processing while the dataset is still being read.

And chunk-wise processing might also be beneficial when compiling a dataset. For example, think of a webservice such as a WFS that responds with a CityJSON dataset to a client request. Although individual `CityObjects` can be constructed and send as a stream to the client with the current CityJSON schema, the WFS implementation would always have to keep the entire `"vertices"` array in main memory and could only send it after the last city object has been sent to the client. If a client requests large parts of a city model, then the `"vertices"` array might quickly grow in size and eat up resources. Likewise, although the client could read the individual city objects from the stream, it would only be able to really process them after the `"vertices"` array has also been received.

A possible solution to this would be to let each city object have its own `"vertices"` array (same for `"material"` and `"texture"`). So all information about the city object would be contained in one Json object.

Well, this is of course a design decision. And there are also reasons for having one common `"vertices"` array, e.g. non-redundant vertices over all city objects.

**Comment by hugoledoux** [comment]
I'm aware of the problem, and this is something we'll address in the coming months. 

My preferred way would be to have a "master" file that links to specific cityjson files, these being self-contained and all of a reasonable size. Nothing needs to be changed. That would of course means that we have software to extract/merge cityjson parts... Should be doable though.

That could be implemented with [3D Tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles) and their tileset. But I haven't read about this yet, so perhaps I'm talking through my hat...

Having each CityObject have its own `"vertices"` is however a solution worth considering. I'm hoping to find an MSc student taking this as a thesis topic (https://3d.bk.tudelft.nl/education/msctopics/#compression-of-cityjson-files), but so far no one showed interest :(

**Comment by clausnagel** [comment]
Linked a discussion in the @3DCityDB development team: https://github.com/3dcitydb/importer-exporter/pull/92.

**Comment by hugoledoux** [comment]
v1.1 has the new type [`"CityJSONFeature"`](https://www.cityjson.org/specs/1.1.0/#text-sequences-and-streaming-with-cityjsonfeature) which solves this more or less
