### ISSUE TITLE
GeometryInstance "boundaries" is unclear

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#60]
The description of the `boundaries` of a GeometryInstance is not clear.

*must have one member with the name "boundaries", whose value is an array containing only one vertex index, which refers to one vertex in the "vertices" property of a CityJSON file. (This is the "referencePoint" in CityGML.)*

I don't know what is the "referencePoint" in CityGML. The centroid of the geometry? The point where to place the geometry?

Better to describe it explicitly, instead of referring to CityGML.

**Comment by kenohori** [comment]
See https://www.cityjson.org/help/dev/realcoords/

**Comment by Alena0915** [comment]
I still got confused. Dose the transformationMatrix contain the incomplete transformation?
 why should we need a reference point? Dose it mean we actually need to do transformation twice? First apply the transformationMatrix  then do a translate according to the reference point?
