### ISSUE TITLE
Indenting is not consistent in schema files.

### ISSUE THREAD

**Issue by KevinWiebe** [cityjson/specs#61]
Some of the schema files do not have consistent indenting.

For example, `metadata.schema.json` , line 352
The elements under "geographicalExtent" are indented twice as much as they should be.

line 360
"temporalExtent" should be lined up with "geographicalExtent" but it is not.

Many other examples.

There are nice formatting tools that can clean this up, and I don't think new versions need to have version changes or anything.

**Comment by hugoledoux** [comment]
oh right, thanks! I'll reformat soon.

PS: you read them all? Nice day you must have had 😜
