### ISSUE TITLE
Suggestion: Have `cityjson` as a file extension for cityjson files

### ISSUE THREAD

**Issue by chow1026** [cityjson/specs#64]
It is not uncommon people work with multiple types of json files: generic json, ndjson (new line json), geojson and cityjson. 

It would make sense if cityjson has its own file extension, so it is easily recognizable compared to other json files in a same directory.

**Comment by liberostelios** [comment]
This would work even better now that we have CityJSON supported by [SchemaStore](https://www.schemastore.org/json/). The some editors (like Visual Studio Code) could do on-the-fly validation by associating a file with our schema based on the file extension. Now, you can only do that if you manually set the `"$schema"` property yourself.

**Comment by derhuerst** [comment]
What about `.city.json`? It would clearly distinguish that we‘re dealing with CityJSON data, but all tools that don‘t know this format specifically would still know that it‘s JSON-based.

**Comment by liberostelios** [comment]
That's a good idea. But on the other hand, we have the already established practice of `.geojson` in the geo field. I don't have a clear opinion.

**Comment by derhuerst** [comment]
> That's a good idea. But on the other hand, we have the already established practice of `.geojson` in the geo field. I don't have a clear opinion.

I've also seen `.geo.json`, but I have no idea how widespread each one is.
