### ISSUE TITLE
Possible inconsistency in specs? - Transport semantics in 1.0.3

### ISSUE THREAD

**Issue by vojtatom** [cityjson/specs#82]
In section [Transportation](https://www.cityjson.org/specs/1.0.3/#transportation), I noticed that the `semantics` object is located outside the `geometry` object. Later in the section [Geometry objects](https://www.cityjson.org/specs/1.0.3/#geometry-objects), it says the `semantics` object may be inside the `geometry` object. 

Did I miss something, or is the example in the Transportation section not valid?

**Comment by hugoledoux** [comment]
oh wow, many thanks, it's an error indeed!

no one has spotted this and it's been there for 1y+, so many thanks 👍

I'll wait to see if you spot another one, then release v1.0.4
