### ISSUE TITLE
Clarify use of parent - children relations for buildings

### ISSUE THREAD

**Issue by clausnagel** [cityjson/specs#99]
In the [2.3 Building](https://www.cityjson.org/specs/1.1.0/#building) chapter, the spec says:

> The installations, furnitures, and subdivisions can have as parents either a "Building" or a "BuildingPart".

Is this meant as example or as restriction? If it's meant as restriction, then why shouldn't an installation or funiture have a "BuildingRoom" as parent? Moreover, neither the Bridge nor the Tunnel chapter have similiar restrictions.

**Comment by hugoledoux** [comment]
It's not a restriction, was an example indeed. There is no way to enforce this in the schemas anyway.

I'll improve the wording, cheers.
